name: Maicon Junge
description: Empreendedorismo, Tecnlogia, Finanças e um pouco mais
meta_description: "Empreendedorismo, Tecnlogia, Finanças e um pouco mais"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "https://maiconjunge.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://maiconjunge.github.io/"
author: "Maicon Junge"

# Disqus config
disqus-shortname: ""
